"use client";

import { formatCurrency, formatPrice, num, resultLabel } from "@/lib/calculations";
import type { Trade, Playbook, DailyReview } from "@/db/schema";

// ── Colors ──
const C = {
  primary: [99, 102, 241] as [number, number, number],
  profit: [34, 197, 94] as [number, number, number],
  loss: [239, 68, 68] as [number, number, number],
  text: [55, 65, 81] as [number, number, number],
  muted: [107, 114, 128] as [number, number, number],
  light: [245, 245, 250] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  headerBg: [30, 30, 45] as [number, number, number],
};

// ── Helpers ──
function fDate(d: Date | string | null | undefined): string {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}
function fTime(d: Date | string | null | undefined): string {
  if (!d) return "";
  return new Date(d).toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: false });
}
function sesLbl(s: string | null | undefined): string {
  if (!s) return "—";
  return s.replace("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

// Dynamic loader so jsPDF is only loaded client-side at call time
async function loadLibs() {
  const jspdfMod = await import("jspdf");
  const atMod = await import("jspdf-autotable");
  const JsPDF = (jspdfMod as any).jsPDF || jspdfMod.default;
  const at = (atMod as any).default || (atMod as any).autoTable || atMod;
  return { JsPDF: JsPDF as typeof jspdfMod.default, autoTable: at as (doc: any, opts: any) => void };
}

function downloadBlob(doc: { output: (t: string) => Blob }, filename: string) {
  const blob = doc.output("blob") as Blob;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 300);
}

// Shared PDF building helpers operating on any jsPDF instance
function addHeader(doc: any, title: string, subtitle: string) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, w, 22, "F");
  doc.setFontSize(14);
  doc.setTextColor(...C.white);
  doc.setFont("helvetica", "bold");
  doc.text("TradeOS", 10, 10);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(title, 10, 17);
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 200);
  doc.text(subtitle, w - 10, 10, { align: "right" });
  doc.text(new Date().toLocaleString("en-US", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" }), w - 10, 16, { align: "right" });
}

function addFooter(doc: any) {
  const pages = doc.internal.pages.length - 1;
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...C.muted);
    doc.text(`Page ${i} of ${pages}`, w / 2, h - 5, { align: "center" });
    doc.text("Generated by TradeOS", 10, h - 5);
  }
}

function secTitle(doc: any, y: number, title: string): number {
  const w = doc.internal.pageSize.getWidth();
  doc.setFontSize(11);
  doc.setTextColor(...C.primary);
  doc.setFont("helvetica", "bold");
  doc.text(title, 10, y);
  doc.setDrawColor(...C.primary);
  doc.setLineWidth(0.3);
  doc.line(10, y + 1.5, w - 10, y + 1.5);
  return y + 7;
}

function kpiRow(doc: any, y: number, items: { label: string; value: string; color?: [number, number, number] }[]): number {
  const w = doc.internal.pageSize.getWidth() - 20;
  const bw = w / items.length;
  for (let i = 0; i < items.length; i++) {
    const x = 10 + i * bw;
    doc.setFillColor(...C.light);
    doc.roundedRect(x + 1, y, bw - 2, 14, 2, 2, "F");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...(items[i].color || C.text));
    doc.text(items[i].value, x + bw / 2, y + 6, { align: "center" });
    doc.setFontSize(6);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...C.muted);
    doc.text(items[i].label.toUpperCase(), x + bw / 2, y + 11, { align: "center" });
  }
  return y + 18;
}

function needsBreak(doc: any, y: number, needed: number): boolean {
  return y + needed > doc.internal.pageSize.getHeight() - 15;
}

// ═══════════════════════════════════════════
// TRADE JOURNAL PDF
// ═══════════════════════════════════════════
export async function exportTradeJournalPDF(trades: Trade[], dateRange: { start: string; end: string }) {
  const { JsPDF, autoTable } = await loadLibs();
  const doc = new JsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const title = "Trade Journal Report";
  const sub = `${fDate(dateRange.start)} — ${fDate(dateRange.end)}`;
  addHeader(doc, title, sub);

  const filtered = trades.filter((t) => {
    const d = new Date(t.entryDate);
    return d >= new Date(dateRange.start) && d <= new Date(dateRange.end + "T23:59:59");
  }).sort((a, b) => new Date(a.entryDate).getTime() - new Date(b.entryDate).getTime());

  const closed = filtered.filter((t) => t.status === "closed");
  const wins = closed.filter((t) => t.outcome === "win");
  const totalPnl = closed.reduce((s, t) => s + num(t.pnl), 0);
  const totalPips = closed.reduce((s, t) => s + num(t.pipsCaptured), 0);

  let y = 28;
  y = secTitle(doc, y, "Performance Summary");
  y = kpiRow(doc, y, [
    { label: "Trades", value: String(filtered.length) },
    { label: "W / L", value: `${wins.length} / ${closed.length - wins.length}` },
    { label: "Win Rate", value: `${closed.length > 0 ? ((wins.length / closed.length) * 100).toFixed(1) : "0"}%`, color: closed.length > 0 && wins.length / closed.length >= 0.5 ? C.profit : C.loss },
    { label: "Net P&L", value: formatCurrency(totalPnl), color: totalPnl >= 0 ? C.profit : C.loss },
    { label: "Total Pips", value: totalPips.toFixed(1), color: totalPips >= 0 ? C.profit : C.loss },
  ]);

  y = secTitle(doc, y, "Table 1 — Complete Trade Log");
  autoTable(doc, {
    startY: y,
    head: [["#", "Date & Time", "Session", "Symbol", "Side", "Entry", "SL", "TP", "Exit", "Pips", "P&L", "R", "Strategy", "Setup", "TF", "Result"]],
    body: filtered.map((t, i) => [
      i + 1, `${fDate(t.entryDate)} ${fTime(t.entryDate)}`, sesLbl(t.session), t.symbol,
      t.direction === "long" ? "BUY" : "SELL", formatPrice(t.entryPrice), formatPrice(t.stopLoss),
      formatPrice(t.takeProfit), formatPrice(t.exitPrice),
      t.pipsCaptured ? `${num(t.pipsCaptured) >= 0 ? "+" : ""}${num(t.pipsCaptured).toFixed(1)}` : "—",
      t.pnl ? formatCurrency(num(t.pnl)) : "—",
      t.rMultiple ? `${num(t.rMultiple) >= 0 ? "+" : ""}${num(t.rMultiple).toFixed(2)}R` : "—",
      t.strategy || "—", t.setup || "—", t.timeframe || "—",
      resultLabel(t),
    ]),
    styles: { fontSize: 6.5, cellPadding: 1.5, textColor: C.text },
    headStyles: { fillColor: C.headerBg, textColor: C.white, fontSize: 6, fontStyle: "bold" },
    alternateRowStyles: { fillColor: C.light },
    columnStyles: { 0: { cellWidth: 7 }, 3: { fontStyle: "bold" } },
    didParseCell: (data: any) => {
      if (data.section === "body" && filtered[data.row.index]) {
        const row = filtered[data.row.index];
        if (data.column.index === 10 && row.pnl) data.cell.styles.textColor = num(row.pnl) >= 0 ? C.profit : C.loss;
        if (data.column.index === 15) { data.cell.styles.textColor = row.outcome === "win" ? C.profit : row.outcome === "loss" ? C.loss : C.text; data.cell.styles.fontStyle = "bold"; }
      }
    },
    margin: { left: 10, right: 10 },
  });
  y = (((doc as any).lastAutoTable)?.finalY ?? 100) + 6;

  // Table 2: Notes
  const withNotes = filtered.filter((t) => t.whatIDid || t.whatIShouldHaveDone || t.notes);
  if (withNotes.length > 0) {
    doc.addPage(); addHeader(doc, title, sub); y = 28;
    y = secTitle(doc, y, "Table 2 — Notes & Reflections");
    autoTable(doc, {
      startY: y,
      head: [["#", "Date · Session", "Symbol", "Result", "P&L", "What I Did", "What I Should Have Done", "Notes"]],
      body: withNotes.map((t, i) => [
        i + 1, `${fDate(t.entryDate)} · ${sesLbl(t.session)} ${fTime(t.entryDate)}`, t.symbol,
        resultLabel(t),
        t.pnl ? formatCurrency(num(t.pnl)) : "—",
        t.whatIDid || "—", t.whatIShouldHaveDone || "—", t.notes || "—",
      ]),
      styles: { fontSize: 6, cellPadding: 2, textColor: C.text, overflow: "linebreak" },
      headStyles: { fillColor: C.headerBg, textColor: C.white, fontSize: 6, fontStyle: "bold" },
      alternateRowStyles: { fillColor: C.light },
      columnStyles: { 0: { cellWidth: 7 }, 5: { cellWidth: 55 }, 6: { cellWidth: 55 }, 7: { cellWidth: 50 } },
      margin: { left: 10, right: 10 },
    });
    y = (((doc as any).lastAutoTable)?.finalY ?? 100) + 6;
  }

  // Table 3: Strengths & Weaknesses
  const withTags = filtered.filter((t) => ((t.whatWorked as string[]) || []).length > 0 || ((t.mistakes as string[]) || []).length > 0);
  if (withTags.length > 0) {
    if (needsBreak(doc, y, 40)) { doc.addPage(); addHeader(doc, title, sub); y = 28; }
    y = secTitle(doc, y, "Table 3 — Strengths & Weaknesses");
    autoTable(doc, {
      startY: y,
      head: [["#", "Date · Session", "Symbol", "Side", "Result", "P&L", "What Worked", "Mistakes"]],
      body: withTags.map((t, i) => [
        i + 1, `${fDate(t.entryDate)} · ${sesLbl(t.session)} ${fTime(t.entryDate)}`, t.symbol,
        t.direction === "long" ? "BUY" : "SELL",
        resultLabel(t),
        t.pnl ? formatCurrency(num(t.pnl)) : "—",
        ((t.whatWorked as string[]) || []).join(", ") || "—",
        ((t.mistakes as string[]) || []).join(", ") || "—",
      ]),
      styles: { fontSize: 6, cellPadding: 2, textColor: C.text, overflow: "linebreak" },
      headStyles: { fillColor: C.headerBg, textColor: C.white, fontSize: 6, fontStyle: "bold" },
      alternateRowStyles: { fillColor: C.light },
      columnStyles: { 0: { cellWidth: 7 }, 6: { cellWidth: 65, textColor: C.profit }, 7: { cellWidth: 65, textColor: C.loss } },
      margin: { left: 10, right: 10 },
    });
  }

  addFooter(doc);
  downloadBlob(doc, `TradeOS-Journal-${dateRange.start}-to-${dateRange.end}.pdf`);
}

// ═══════════════════════════════════════════
// DASHBOARD PDF
// ═══════════════════════════════════════════
export async function exportDashboardPDF(
  trades: Trade[],
  metrics: { totalPnl: number; winRate: number; profitFactor: number; expectancy: number; avgWin: number; avgLoss: number; largestWin: number; largestLoss: number; maxDrawdown: number; sharpeRatio: number; maxConsecutiveWins: number; maxConsecutiveLosses: number; avgRiskReward: number; totalTrades: number; winningTrades: number; losingTrades: number },
  startingBalance: number,
) {
  const { JsPDF, autoTable } = await loadLibs();
  const doc = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  addHeader(doc, "Performance Dashboard", "Account Overview");

  let y = 28;
  const bal = startingBalance + metrics.totalPnl;
  const ret = startingBalance > 0 ? ((bal - startingBalance) / startingBalance) * 100 : 0;

  y = secTitle(doc, y, "Account Overview");
  y = kpiRow(doc, y, [
    { label: "Starting", value: formatCurrency(startingBalance) },
    { label: "Current", value: formatCurrency(bal), color: bal >= startingBalance ? C.profit : C.loss },
    { label: "Net P&L", value: formatCurrency(metrics.totalPnl), color: metrics.totalPnl >= 0 ? C.profit : C.loss },
    { label: "Return", value: `${ret >= 0 ? "+" : ""}${ret.toFixed(2)}%`, color: ret >= 0 ? C.profit : C.loss },
  ]);

  y = secTitle(doc, y, "Key Metrics");
  y = kpiRow(doc, y, [
    { label: "Win Rate", value: `${metrics.winRate}%`, color: metrics.winRate >= 50 ? C.profit : C.loss },
    { label: "Profit Factor", value: metrics.profitFactor === Infinity ? "∞" : metrics.profitFactor.toFixed(2), color: metrics.profitFactor >= 1 ? C.profit : C.loss },
    { label: "Sharpe", value: metrics.sharpeRatio.toFixed(2) },
    { label: "Max DD", value: formatCurrency(metrics.maxDrawdown), color: C.loss },
  ]);
  y = kpiRow(doc, y, [
    { label: "Avg Win", value: formatCurrency(metrics.avgWin), color: C.profit },
    { label: "Avg Loss", value: formatCurrency(metrics.avgLoss), color: C.loss },
    { label: "Expectancy", value: formatCurrency(metrics.expectancy), color: metrics.expectancy >= 0 ? C.profit : C.loss },
    { label: "Avg R:R", value: metrics.avgRiskReward.toFixed(2) },
  ]);

  y = secTitle(doc, y, "Detailed Statistics");
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value", "Metric", "Value"]],
    body: [
      ["Total Trades", String(metrics.totalTrades), "Winning", String(metrics.winningTrades)],
      ["Losing", String(metrics.losingTrades), "Win Rate", `${metrics.winRate}%`],
      ["Largest Win", formatCurrency(metrics.largestWin), "Largest Loss", formatCurrency(metrics.largestLoss)],
      ["Max Win Streak", String(metrics.maxConsecutiveWins), "Max Loss Streak", String(metrics.maxConsecutiveLosses)],
    ],
    styles: { fontSize: 8, cellPadding: 3, textColor: C.text },
    headStyles: { fillColor: C.headerBg, textColor: C.white, fontStyle: "bold" },
    alternateRowStyles: { fillColor: C.light },
    columnStyles: { 0: { fontStyle: "bold" }, 2: { fontStyle: "bold" } },
    margin: { left: 10, right: 10 },
  });
  y = (((doc as any).lastAutoTable)?.finalY ?? 150) + 6;

  const recent = trades.filter((t) => t.status === "closed").sort((a, b) => new Date(b.entryDate).getTime() - new Date(a.entryDate).getTime()).slice(0, 15);
  if (recent.length > 0) {
    if (needsBreak(doc, y, 30)) { doc.addPage(); addHeader(doc, "Performance Dashboard", ""); y = 28; }
    y = secTitle(doc, y, "Recent Trades");
    autoTable(doc, {
      startY: y,
      head: [["Date", "Session", "Symbol", "Side", "P&L", "R", "Strategy", "Result"]],
      body: recent.map((t) => [
        `${fDate(t.entryDate)} ${fTime(t.entryDate)}`, sesLbl(t.session), t.symbol,
        t.direction === "long" ? "BUY" : "SELL",
        t.pnl ? formatCurrency(num(t.pnl)) : "—",
        t.rMultiple ? `${num(t.rMultiple) >= 0 ? "+" : ""}${num(t.rMultiple).toFixed(2)}R` : "—",
        t.strategy || "—", resultLabel(t),
      ]),
      styles: { fontSize: 7, cellPadding: 2, textColor: C.text },
      headStyles: { fillColor: C.headerBg, textColor: C.white, fontSize: 7, fontStyle: "bold" },
      alternateRowStyles: { fillColor: C.light },
      didParseCell: (data: any) => {
        if (data.section === "body" && recent[data.row.index]) {
          const r = recent[data.row.index];
          if (data.column.index === 4 && r.pnl) data.cell.styles.textColor = num(r.pnl) >= 0 ? C.profit : C.loss;
          if (data.column.index === 7) { data.cell.styles.textColor = r.outcome === "win" ? C.profit : r.outcome === "loss" ? C.loss : C.text; data.cell.styles.fontStyle = "bold"; }
        }
      },
      margin: { left: 10, right: 10 },
    });
  }

  addFooter(doc);
  downloadBlob(doc, `TradeOS-Dashboard-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ═══════════════════════════════════════════
// PLAYBOOK PDF
// ═══════════════════════════════════════════
export async function exportPlaybookPDF(playbooks: Playbook[], trades: Trade[]) {
  const { JsPDF } = await loadLibs();
  const doc = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  addHeader(doc, "Trading Playbook", `${playbooks.length} strategies`);
  let y = 28;

  if (playbooks.length === 0) {
    doc.setFontSize(10); doc.setTextColor(...C.muted);
    doc.text("No playbooks created yet.", 10, y);
  } else {
    for (let pi = 0; pi < playbooks.length; pi++) {
      const pb = playbooks[pi];
      if (needsBreak(doc, y, 50)) { doc.addPage(); addHeader(doc, "Trading Playbook", ""); y = 28; }
      const pbT = trades.filter((t) => t.strategy === pb.name && t.status === "closed");
      const w = pbT.filter((t) => t.outcome === "win");
      const pnl = pbT.reduce((s, t) => s + num(t.pnl), 0);
      y = secTitle(doc, y, `${pi + 1}. ${pb.name}`);
      if (pb.description) {
        doc.setFontSize(8); doc.setTextColor(...C.text); doc.setFont("helvetica", "normal");
        const ln = doc.splitTextToSize(pb.description, 180); doc.text(ln, 10, y); y += ln.length * 3.5 + 2;
      }
      y = kpiRow(doc, y, [
        { label: "Trades", value: String(pbT.length) },
        { label: "Win Rate", value: pbT.length > 0 ? `${((w.length / pbT.length) * 100).toFixed(0)}%` : "—", color: pbT.length > 0 && w.length / pbT.length >= 0.5 ? C.profit : C.loss },
        { label: "P&L", value: formatCurrency(pnl), color: pnl >= 0 ? C.profit : C.loss },
        { label: "Market", value: pb.marketType?.toUpperCase() || "Any" },
      ]);
      for (const [label, items] of [["Entry Conditions", (pb.entryConditions as string[]) || []], ["Exit Conditions", (pb.exitConditions as string[]) || []], ["Rules", (pb.rules as string[]) || []]] as [string, string[]][]) {
        if (items.length > 0) {
          if (needsBreak(doc, y, items.length * 4 + 8)) { doc.addPage(); addHeader(doc, "Trading Playbook", ""); y = 28; }
          doc.setFontSize(8); doc.setTextColor(...C.primary); doc.setFont("helvetica", "bold");
          doc.text(label + ":", 10, y); y += 4;
          doc.setTextColor(...C.text); doc.setFont("helvetica", "normal"); doc.setFontSize(7);
          for (const it of items) { doc.text(`•  ${it}`, 14, y); y += 4; }
          y += 2;
        }
      }
      y += 6;
    }
  }

  addFooter(doc);
  downloadBlob(doc, `TradeOS-Playbook-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ═══════════════════════════════════════════
// REVIEWS PDF
// ═══════════════════════════════════════════
export async function exportReviewsPDF(reviews: DailyReview[], trades: Trade[]) {
  const { JsPDF } = await loadLibs();
  const doc = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  addHeader(doc, "Daily Reviews Report", `${reviews.length} reviews`);
  let y = 28;

  if (reviews.length === 0) {
    doc.setFontSize(10); doc.setTextColor(...C.muted);
    doc.text("No daily reviews created yet.", 10, y);
  } else {
    for (const r of reviews) {
      if (needsBreak(doc, y, 45)) { doc.addPage(); addHeader(doc, "Daily Reviews Report", ""); y = 28; }
      const ds = new Date(r.date).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" });
      const dayT = trades.filter((t) => t.status === "closed" && t.exitDate && fDate(t.exitDate) === fDate(r.date));
      const dp = dayT.reduce((s, t) => s + num(t.pnl), 0);
      y = secTitle(doc, y, ds);
      y = kpiRow(doc, y, [
        { label: "Rating", value: "★".repeat(parseInt(r.rating)) + "☆".repeat(5 - parseInt(r.rating)) },
        { label: "Trades", value: String(dayT.length) },
        { label: "Day P&L", value: formatCurrency(dp), color: dp >= 0 ? C.profit : C.loss },
        { label: "Plan", value: r.followedPlan === true ? "Yes" : r.followedPlan === false ? "No" : "—", color: r.followedPlan === true ? C.profit : r.followedPlan === false ? C.loss : C.text },
      ]);
      for (const [label, val] of [["Pre-Market Plan", r.preMarketPlan], ["Post-Market Review", r.postMarketReview], ["Lessons Learned", r.lessonsLearned]] as [string, string | null][]) {
        if (val) {
          if (needsBreak(doc, y, 10)) { doc.addPage(); addHeader(doc, "Daily Reviews Report", ""); y = 28; }
          doc.setFontSize(7); doc.setTextColor(...C.primary); doc.setFont("helvetica", "bold");
          doc.text(label + ":", 10, y); y += 3.5;
          doc.setTextColor(...C.text); doc.setFont("helvetica", "normal");
          const ln = doc.splitTextToSize(val, 180); doc.text(ln, 10, y); y += ln.length * 3.5 + 2;
        }
      }
      y += 5;
    }
  }

  addFooter(doc);
  downloadBlob(doc, `TradeOS-Reviews-${new Date().toISOString().split("T")[0]}.pdf`);
}

// ═══════════════════════════════════════════
// INSIGHTS PDF
// ═══════════════════════════════════════════
export async function exportInsightsPDF(
  _trades: Trade[],
  patterns: { type: string; pattern: string; actionable: string; financialImpact: number; winRate: number; trades: number }[],
  mistakes: { mistake: string; totalLoss: number; occurrences: number; percentOfLosses: number }[],
  whatWorked: { factor: string; totalProfit: number; occurrences: number }[],
  dateRange: { start: string; end: string },
) {
  const { JsPDF, autoTable } = await loadLibs();
  const doc = new JsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const sub = `${fDate(dateRange.start)} — ${fDate(dateRange.end)}`;
  addHeader(doc, "Insight Engine Report", sub);
  let y = 28;

  if (patterns.length > 0) {
    y = secTitle(doc, y, "Discovered Patterns");
    autoTable(doc, {
      startY: y,
      head: [["Type", "Pattern", "WR", "Trades", "Impact", "Recommendation"]],
      body: patterns.map((p) => [
        p.type === "winning" ? "✓ WIN" : "✗ LOSS", p.pattern, `${p.winRate}%`, String(p.trades),
        `${p.financialImpact >= 0 ? "+" : ""}${formatCurrency(p.financialImpact)}`, p.actionable,
      ]),
      styles: { fontSize: 7, cellPadding: 2, textColor: C.text, overflow: "linebreak" },
      headStyles: { fillColor: C.headerBg, textColor: C.white, fontSize: 7, fontStyle: "bold" },
      alternateRowStyles: { fillColor: C.light },
      columnStyles: { 5: { cellWidth: 55 } },
      didParseCell: (data: any) => {
        if (data.section === "body") {
          if (data.column.index === 0) { data.cell.styles.textColor = patterns[data.row.index]?.type === "winning" ? C.profit : C.loss; data.cell.styles.fontStyle = "bold"; }
          if (data.column.index === 4) data.cell.styles.textColor = patterns[data.row.index]?.financialImpact >= 0 ? C.profit : C.loss;
        }
      },
      margin: { left: 10, right: 10 },
    });
    y = (((doc as any).lastAutoTable)?.finalY ?? 100) + 6;
  }

  if (whatWorked.length > 0) {
    if (needsBreak(doc, y, 30)) { doc.addPage(); addHeader(doc, "Insight Engine Report", sub); y = 28; }
    y = secTitle(doc, y, "Profitable Habits");
    autoTable(doc, {
      startY: y, head: [["#", "Factor", "Count", "Total Profit"]],
      body: whatWorked.map((w, i) => [i + 1, w.factor, `${w.occurrences}×`, `+${formatCurrency(w.totalProfit)}`]),
      styles: { fontSize: 8, cellPadding: 2.5, textColor: C.text },
      headStyles: { fillColor: C.headerBg, textColor: C.white, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [240, 253, 244] },
      columnStyles: { 3: { textColor: C.profit, fontStyle: "bold" } },
      margin: { left: 10, right: 10 },
    });
    y = (((doc as any).lastAutoTable)?.finalY ?? 100) + 6;
  }

  if (mistakes.length > 0) {
    if (needsBreak(doc, y, 30)) { doc.addPage(); addHeader(doc, "Insight Engine Report", sub); y = 28; }
    y = secTitle(doc, y, "Costly Mistakes");
    autoTable(doc, {
      startY: y, head: [["#", "Mistake", "Count", "% Losses", "Total Cost"]],
      body: mistakes.map((m, i) => [i + 1, m.mistake, `${m.occurrences}×`, `${m.percentOfLosses}%`, `-${formatCurrency(m.totalLoss)}`]),
      styles: { fontSize: 8, cellPadding: 2.5, textColor: C.text },
      headStyles: { fillColor: C.headerBg, textColor: C.white, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [254, 242, 242] },
      columnStyles: { 4: { textColor: C.loss, fontStyle: "bold" } },
      margin: { left: 10, right: 10 },
    });
  }

  addFooter(doc);
  downloadBlob(doc, `TradeOS-Insights-${dateRange.start}-to-${dateRange.end}.pdf`);
}
